# Generated by Django 4.2.4 on 2023-09-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionariosapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='numerotel',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='funcid',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionariosapi.departamento'),
        ),
    ]
