# Generated by Django 4.2.4 on 2023-09-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionariosapi', '0002_departamento_rename_numerotel_funcionario_telefone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='id',
            new_name='id_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nomecompleto',
            new_name='nome_completo',
        ),
    ]
